### ISSUE TITLE
API versioning

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#28]
API versioning is an important aspect of any API. How can the connect platform handle this aspect especially with changing API interfaces, this can be of detrimental impact on users of you service and needs to be addressed by the platform as a way of enforcing these API contracts depending on the version of usage.

This is particularly important in the case of a third-party packages market place.

Articles worth taking a look at:
[Introduction to API Versioning Best Practices](https://nordicapis.com/introduction-to-api-versioning-best-practices/)
[Versioning a REST API](https://www.baeldung.com/rest-versioning)
[Best practices for API versioning?](https://stackoverflow.com/questions/389169/best-practices-for-api-versioning)

**Comment by loreanvictor** [comment]
@must based on semver versioning which is being used for the platform itself, right now we are before the first initial release which in turn means the api can go up and down according to development needs. when we hit the 1.0.0 mark, we should be making updates to the api much more carefully and when we hit the 2.0.0 mark, well then we should figure out how to prevent a disaster of repository fragmentation.

for external packages, packages developed right now are subject to drastic changes and failures for the very same reason and can cherish the stability of post-1.0.0 when it comes.

anyways closing this issue for now. we can re-open it in the future when this issue is up.

**Comment by must** [comment]
I agree. Please label it as a future idea or something like that.
