### ISSUE TITLE
logging errors

### ISSUE THREAD

**Issue by must** [CONNECT-platform/connect-platform#35]
Is a logging mechanism for errors provided by the platform? @loreanvictor 

Updated with detailed description:
So my question is more related to run-time errors as a way to provide a mechanism for logging errors that are not to be expected under normal circumstances and hence provide a way for the visual developers to debug their visual code. This is especially important for production as unforeseen complexities (Bugs) will eventually arise (Murphy's law).

Also logging can provide other levels of information (Debug, Info etc..)

**Comment by loreanvictor** [comment]
@must not directly a logging mechanism, but the `test` feature will record some errors and display the details of those errors when they happen during runtime. of course the reliability of this feature is currently not high as it is not able to catch all errors, additionally syntax errors cannot be caught by the platform regardless since they cannot be loaded in the first place.

**Comment by must** [comment]
So my question is more related to run-time errors as a way to provide a mechanism for logging errors that are not to be expected under normal circumstances and hence provide a way for the visual developers to debug their visual code. This is especially important for production as unforeseen complexities (Bugs) will eventually arise (Murphy's law).

**Comment by loreanvictor** [comment]
yes one nice solution for that is to actually record (using the same recorder tool used for **test** and **watch** features) to record a random percentage of the execution of nodes in production. however before that can happen first the recorder itself needs to become more robust.

p.s. can you clarify the original message so that other people dont mistakenly create duplicate issues based on this?
